#include <filesystem>
#include <iostream>
#include <pqxx/pqxx> 
#include <vector>
#include "nlohmann/json.hpp"
#include <fstream>
#include "helper.h"
#include <fmt/format.h> 

using namespace std;
using namespace pqxx;
using json = nlohmann::json;

int main(int argc, char* argv[]) {
   std::string GAME_DIRECTORY="game_data"; 
   
   try {
      connection C("dbname = ug4 user = postgres password = postgres \
      hostaddr = 127.0.0.1 port = 5432");
      if (C.is_open()) {
         cout << "Opened database successfully: " << C.dbname() << endl;
         
         // FILE LOOPING MECHANISM GENERATED BY AI 
         std::vector<std::filesystem::path> json_files;
         if (std::filesystem::exists(GAME_DIRECTORY)) {
            for (const auto& entry : std::filesystem::recursive_directory_iterator(GAME_DIRECTORY)) {
               if (entry.is_regular_file() && entry.path().extension() == ".json") {
                  json_files.push_back(entry.path());
               }
            }
         }

         if (json_files.empty()) {
            cout << "No .json files found under " << GAME_DIRECTORY << endl;
         } else {
            cout << "Found " << json_files.size() << " .json file(s) under " << GAME_DIRECTORY << endl;
         }

         for (const auto& json_path : json_files) {
            cout << "Processing: " << json_path.string() << endl;
            
            std::ifstream i(json_path.string());
            json j; 
            i >> j; 

            json games = j["games"];
            
            for (const auto& game : games) {
               /* Create SQL statement */
               std::string black = game["black"]; 
               std::string black_version = game["black_version"]; 
               
               std::string white = game["white"]; 
               std::string white_version = game["white_version"]; 

               std::string game_sequence = join(game["moves"], ","); 

               std::string winner = game["winner"]; 
               
               // TODO: Fix SQL injection 
               std::string sql =  fmt::format("INSERT INTO games (black,black_version,white,white_version,game_sequence, winner) VALUES (\'{}\',\'{}\',\'{}\',\'{}\',\'{}\',\'{}\');", black, black_version, white, white_version, game_sequence, winner); 

               /* Create a transactional object. */
               work W(C);
               
               /* Execute SQL query */
               W.exec( sql );
               W.commit();
               cout << "Records created successfully for " << json_path.string() << endl;
            }
         }

      } else {
         cout << "Can't open database" << endl;
         return 1;
      }
   } catch (const std::exception &e) {
      cerr << e.what() << std::endl;
      return 1;
   }
}